#!/bin/sh
# ci_post_clone.sh — Xcode Cloud runs this after cloning the repo.
# Generates Secrets.xcconfig from the TMDB_API_TOKEN environment variable
# set in Xcode Cloud's workflow settings.

set -e

CONFIG_DIR="$CI_PRIMARY_REPOSITORY_PATH/FlickSwiper/Config"

if [ -n "$TMDB_API_TOKEN" ]; then
    echo "// Auto-generated by ci_post_clone.sh" > "$CONFIG_DIR/Secrets.xcconfig"
    echo "TMDB_API_TOKEN = $TMDB_API_TOKEN" >> "$CONFIG_DIR/Secrets.xcconfig"
    echo "✅ Secrets.xcconfig created from environment variable."
else
    echo "⚠️ TMDB_API_TOKEN not set — build will proceed without API token."
fi
